# fly.toml app configuration file generated for mushrooms on 2023-04-24T18:17:13+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app_name = "mushrooms"
primary_region = "waw"

[build]
  image = "raudzius/mushrooms:latest"

[env]
ASPNETCORE_URLS="http://+:8080"
StripeSettings__PublishableKey="pk_test_51K80mMDaCJKT60BEvA0bvrGH1sfobCf2pFvqxUsP87DXpvSdnHUzrSTfo6JHmsns2XOCXUp1SHbePZNXwbk0kwCf002IGIp4jK"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
